server:
  port: 8017

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sda?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    druid:
      web-stat-filter:
        enabled: false

logging:
  level:
    cn:
      edu:
        nju:
          software:
            sda:
              app:
                dao: debug
sda:
  properties: application-sda.properties