server:
  port: 8093

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sda?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

sda:
  properties: application-sdaaliyun.properties
